# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install requirements run tests
        run: |
          pip install virtualenv
          virtualenv env
          source env/bin/activate
          cd Parcial3_BigData/Parcial3-BigData-main/Punto_Productores
          pip install -r requirements.txt
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIATNTDJLQZBCXBLJOH
          aws-secret-access-key: 3qcy4QDtdL73Gwjy9TRcFRXFS7XUAGSyObvhqs9s
          aws-session-token: FwoGZXIvYXdzEFEaDIt998WyKNsW4qleyiLJAdl0/G7uJ5r5k59bd17xO2bIpsDqQSDckGpcbV3OUQjEBtioZL80YPsjkyGZamwTl6dhHwfxaUV5nOCunGEY7o6ophQPttWwCGeaLzpOvI+ACIe/RYg1vglRIMoHojvn/2sloooGbEC4TeSE6T/MP32bECuHIATnFDKORlfTPuyToBMfC+rcN2mXusliKTgkoARJo8i8hJiir4YEVy3D8gqXEJJ/FWva5oUpxcqFAYC0HnPSytO5C8IlKi6iLIBNMPi50pOjpZ1P7CjLgNOjBjItdyIllQdYNWl82oPEl2XlNH6LuCUSyNKDMOdENEiMSbm2S1WPj2zWZRxDnOu3
          aws-region: us-east-1 
          
      - name: Pytest
        run: | 
          source env/bin/activate
          pytest
      
      - name: flake8
        run: |
          source env/bin/activate
          
          flake8 Parcial3_BigData/Parcial3-BigData-main/Punto_Productores/productor1.py
          flake8 Parcial3_BigData/Parcial3-BigData-main/Punto_Productores/consumidorInferior.py
          flake8 Parcial3_BigData/Parcial3-BigData-main/Punto_Productores/productor2.py
          flake8 Parcial3_BigData/Parcial3-BigData-main/Punto_Productores/consumidorSuperior.py
          flake8 Parcial3_BigData/Parcial3-BigData-main/Punto_Productores/test_consumidor.py
          
